export const queryKeys = {
  currentUser: ['current-user'] as const,
  accessibleTenants: ['accessible-tenants'] as const,
  campaigns: (params?: unknown) => ['campaigns', params ?? {}] as const,
  campaign: (id: string) => ['campaign', id] as const,
  eventSummary: (params?: unknown) => ['event-summary', params ?? {}] as const,
  eventTimeseries: (params?: unknown) => ['event-timeseries', params ?? {}] as const,
  venues: (params?: unknown) => ['venues', params ?? {}] as const,
  venue: (id: string) => ['venue', id] as const,
  tenants: (params?: unknown) => ['tenants', params ?? {}] as const,
  tenant: (id: string) => ['tenant', id] as const,
  tenantUsers: (tenantId: string) => ['tenant-users', tenantId] as const,
  tenantUser: (tenantId: string, userId: string) => ['tenant-user', tenantId, userId] as const,
  campaignNotificationConfig: (campaignId: string) => ['campaign-notification-config', campaignId] as const,
  audienceMetrics: () => ['audience', 'metrics'] as const,
  audienceGrowth: (params?: unknown) => ['audience', 'growth', params ?? {}] as const,
  audienceDevices: (params?: unknown) => ['audience', 'devices', params ?? {}] as const,
  audienceDevice: (deviceId: string) => ['audience', 'device', deviceId] as const,
  audienceSegmentation: () => ['audience', 'segmentation'] as const,
  uploads: (params?: unknown) => ['uploads', params ?? {}] as const,
}

