/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectTenantRouteImport } from './routes/select-tenant'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as DashboardVenuesRouteImport } from './routes/dashboard/venues'
import { Route as DashboardAudienceRouteImport } from './routes/dashboard/audience'
import { Route as Dashboard_layoutRouteImport } from './routes/dashboard/__layout'
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns/$campaignId'
import { Route as PlatformTenantsIndexRouteImport } from './routes/platform/tenants/index'
import { Route as CampaignsCampaignIdLocationsRouteImport } from './routes/campaigns/$campaignId.locations'
import { Route as CampaignsCampaignIdEditRouteImport } from './routes/campaigns/$campaignId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectTenantRoute = SelectTenantRouteImport.update({
  id: '/select-tenant',
  path: '/select-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVenuesRoute = DashboardVenuesRouteImport.update({
  id: '/dashboard/venues',
  path: '/dashboard/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAudienceRoute = DashboardAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => DashboardRoute,
} as any)
const Dashboard_layoutRoute = Dashboard_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => DashboardRoute,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformTenantsIndexRoute = PlatformTenantsIndexRouteImport.update({
  id: '/platform/tenants/',
  path: '/platform/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdLocationsRoute =
  CampaignsCampaignIdLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdEditRoute = CampaignsCampaignIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CampaignsCampaignIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-tenant': typeof SelectTenantRoute
  '/signup': typeof SignupRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/dashboard': typeof Dashboard_layoutRoute
  '/dashboard/audience': typeof DashboardAudienceRoute
  '/dashboard/venues': typeof DashboardVenuesRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/locations': typeof CampaignsCampaignIdLocationsRoute
  '/platform/tenants': typeof PlatformTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-tenant': typeof SelectTenantRoute
  '/signup': typeof SignupRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/audience': typeof DashboardAudienceRoute
  '/dashboard/venues': typeof DashboardVenuesRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/locations': typeof CampaignsCampaignIdLocationsRoute
  '/platform/tenants': typeof PlatformTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-tenant': typeof SelectTenantRoute
  '/signup': typeof SignupRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/dashboard/__layout': typeof Dashboard_layoutRoute
  '/dashboard/audience': typeof DashboardAudienceRoute
  '/dashboard/venues': typeof DashboardVenuesRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/locations': typeof CampaignsCampaignIdLocationsRoute
  '/platform/tenants/': typeof PlatformTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/select-tenant'
    | '/signup'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/dashboard'
    | '/dashboard/audience'
    | '/dashboard/venues'
    | '/campaigns'
    | '/dashboard/'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/locations'
    | '/platform/tenants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/select-tenant'
    | '/signup'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/dashboard'
    | '/dashboard/audience'
    | '/dashboard/venues'
    | '/campaigns'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/locations'
    | '/platform/tenants'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/select-tenant'
    | '/signup'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/dashboard/__layout'
    | '/dashboard/audience'
    | '/dashboard/venues'
    | '/campaigns/'
    | '/dashboard/'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/locations'
    | '/platform/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectTenantRoute: typeof SelectTenantRoute
  SignupRoute: typeof SignupRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRouteWithChildren
  CampaignsNewRoute: typeof CampaignsNewRoute
  DashboardVenuesRoute: typeof DashboardVenuesRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  PlatformTenantsIndexRoute: typeof PlatformTenantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-tenant': {
      id: '/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof SelectTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/venues': {
      id: '/dashboard/venues'
      path: '/dashboard/venues'
      fullPath: '/dashboard/venues'
      preLoaderRoute: typeof DashboardVenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/audience': {
      id: '/dashboard/audience'
      path: '/audience'
      fullPath: '/dashboard/audience'
      preLoaderRoute: typeof DashboardAudienceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/__layout': {
      id: '/dashboard/__layout'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof Dashboard_layoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/tenants/': {
      id: '/platform/tenants/'
      path: '/platform/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof PlatformTenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/locations': {
      id: '/campaigns/$campaignId/locations'
      path: '/locations'
      fullPath: '/campaigns/$campaignId/locations'
      preLoaderRoute: typeof CampaignsCampaignIdLocationsRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/edit': {
      id: '/campaigns/$campaignId/edit'
      path: '/edit'
      fullPath: '/campaigns/$campaignId/edit'
      preLoaderRoute: typeof CampaignsCampaignIdEditRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
  }
}

interface CampaignsCampaignIdRouteChildren {
  CampaignsCampaignIdEditRoute: typeof CampaignsCampaignIdEditRoute
  CampaignsCampaignIdLocationsRoute: typeof CampaignsCampaignIdLocationsRoute
}

const CampaignsCampaignIdRouteChildren: CampaignsCampaignIdRouteChildren = {
  CampaignsCampaignIdEditRoute: CampaignsCampaignIdEditRoute,
  CampaignsCampaignIdLocationsRoute: CampaignsCampaignIdLocationsRoute,
}

const CampaignsCampaignIdRouteWithChildren =
  CampaignsCampaignIdRoute._addFileChildren(CampaignsCampaignIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectTenantRoute: SelectTenantRoute,
  SignupRoute: SignupRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRouteWithChildren,
  CampaignsNewRoute: CampaignsNewRoute,
  DashboardVenuesRoute: DashboardVenuesRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  PlatformTenantsIndexRoute: PlatformTenantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
